version: '2'

services:
  app:
    build: app/.
    container_name: dcb_${ENV}
    env_file:
      - app/.env
    tty: true
    stdin_open: true
    container_name: coin_predictator_app

  aerospike:
    image: aerospike:4.5.3.3
    container_name: coin_predictator_aerospike